version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: logsight_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  web_app:
    build: . .
    container_name: web_5
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/logsight_db
      depends_on:
      db:
      condition: service_healthy
    volumes: 
      - ./data:/app/uploads

volumes:
  pgdata:


